// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	Request
	FileRequest
	ReadRequest
	ReadResponse
	StatResponse
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Request 请求结构
type Request struct {
	Id int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// FileRequest 响应结构
type FileRequest struct {
	Filename string `protobuf:"bytes,1,opt,name=Filename" json:"Filename,omitempty"`
}

func (m *FileRequest) Reset()                    { *m = FileRequest{} }
func (m *FileRequest) String() string            { return proto1.CompactTextString(m) }
func (*FileRequest) ProtoMessage()               {}
func (*FileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

// ReadRequest 响应结构
type ReadRequest struct {
	Id     int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=Offset" json:"Offset,omitempty"`
	Size   int64 `protobuf:"varint,3,opt,name=Size" json:"Size,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto1.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

// ReadResponse 响应结构
type ReadResponse struct {
	Size int64  `protobuf:"varint,1,opt,name=Size" json:"Size,omitempty"`
	Date []byte `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`
	EOF  bool   `protobuf:"varint,3,opt,name=EOF" json:"EOF,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto1.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ReadResponse) GetDate() []byte {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ReadResponse) GetEOF() bool {
	if m != nil {
		return m.EOF
	}
	return false
}

// StateResponse 响应结构
type StatResponse struct {
	Type         string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	Size         int64  `protobuf:"varint,2,opt,name=Size" json:"Size,omitempty"`
	LastModified string `protobuf:"bytes,3,opt,name=LastModified" json:"LastModified,omitempty"`
}

func (m *StatResponse) Reset()                    { *m = StatResponse{} }
func (m *StatResponse) String() string            { return proto1.CompactTextString(m) }
func (*StatResponse) ProtoMessage()               {}
func (*StatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StatResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StatResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StatResponse) GetLastModified() string {
	if m != nil {
		return m.LastModified
	}
	return ""
}

// StateResponse 响应结构
type Response struct {
	Id     int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Result bool  `protobuf:"varint,2,opt,name=Result" json:"Result,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto1.RegisterType((*Request)(nil), "proto.Request")
	proto1.RegisterType((*FileRequest)(nil), "proto.FileRequest")
	proto1.RegisterType((*ReadRequest)(nil), "proto.ReadRequest")
	proto1.RegisterType((*ReadResponse)(nil), "proto.ReadResponse")
	proto1.RegisterType((*StatResponse)(nil), "proto.StatResponse")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FileTransfer service

type FileTransferClient interface {
	Open(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*Response, error)
	Close(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Stat(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*StatResponse, error)
	ReadAt(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type fileTransferClient struct {
	cc *grpc.ClientConn
}

func NewFileTransferClient(cc *grpc.ClientConn) FileTransferClient {
	return &fileTransferClient{cc}
}

func (c *fileTransferClient) Open(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.fileTransfer/Open", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferClient) Close(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.fileTransfer/Close", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferClient) Stat(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	out := new(StatResponse)
	err := grpc.Invoke(ctx, "/proto.fileTransfer/Stat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferClient) ReadAt(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/proto.fileTransfer/ReadAt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileTransfer service

type FileTransferServer interface {
	Open(context.Context, *FileRequest) (*Response, error)
	Close(context.Context, *Request) (*Response, error)
	Stat(context.Context, *FileRequest) (*StatResponse, error)
	ReadAt(context.Context, *ReadRequest) (*ReadResponse, error)
}

func RegisterFileTransferServer(s *grpc.Server, srv FileTransferServer) {
	s.RegisterService(&_FileTransfer_serviceDesc, srv)
}

func _FileTransfer_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.fileTransfer/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServer).Open(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransfer_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.fileTransfer/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServer).Close(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransfer_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.fileTransfer/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServer).Stat(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransfer_ReadAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServer).ReadAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.fileTransfer/ReadAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServer).ReadAt(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileTransfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.fileTransfer",
	HandlerType: (*FileTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _FileTransfer_Open_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _FileTransfer_Close_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _FileTransfer_Stat_Handler,
		},
		{
			MethodName: "ReadAt",
			Handler:    _FileTransfer_ReadAt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto1.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0xee, 0x8f, 0xed, 0x59, 0x51, 0x89, 0x20, 0x75, 0x57, 0x92, 0x2b, 0x15, 0x1c,
	0xb8, 0x3d, 0x81, 0xa8, 0xc3, 0x82, 0x52, 0xc8, 0x76, 0xe5, 0x5d, 0x34, 0xa7, 0x50, 0xa8, 0x6d,
	0x6d, 0xb2, 0x0b, 0x7d, 0x4b, 0xdf, 0x48, 0x92, 0xb6, 0x59, 0x84, 0xed, 0x2a, 0xe7, 0xfb, 0xf2,
	0xe5, 0x97, 0x9c, 0x1c, 0x08, 0x9b, 0xfa, 0x63, 0x5e, 0x37, 0x95, 0xaa, 0xc8, 0xd8, 0x2c, 0xf4,
	0x02, 0x8e, 0x18, 0x7e, 0x6d, 0x51, 0x2a, 0x72, 0x0c, 0x7e, 0x22, 0x62, 0xef, 0xd2, 0xbb, 0x1a,
	0x32, 0x3f, 0x11, 0xf4, 0x1a, 0xa6, 0xab, 0xbc, 0xc0, 0x7e, 0x7b, 0x06, 0x81, 0x96, 0x25, 0xff,
	0x44, 0x13, 0x0a, 0x99, 0xd5, 0x34, 0x81, 0x29, 0x43, 0x2e, 0x0e, 0x90, 0xc8, 0x39, 0x4c, 0xd2,
	0x2c, 0x93, 0xa8, 0x62, 0xdf, 0x78, 0x9d, 0x22, 0x04, 0x46, 0xeb, 0xfc, 0x07, 0xe3, 0xa1, 0x71,
	0x4d, 0x4d, 0x9f, 0x21, 0x6a, 0x51, 0xb2, 0xae, 0x4a, 0x89, 0x36, 0xe3, 0xed, 0x32, 0xda, 0x7b,
	0xe4, 0x0a, 0x0d, 0x2d, 0x62, 0xa6, 0x26, 0xa7, 0x30, 0x7c, 0x4a, 0x57, 0x06, 0x15, 0x30, 0x5d,
	0xd2, 0x37, 0x88, 0xd6, 0x8a, 0x2b, 0x97, 0xb4, 0xf9, 0xae, 0xfb, 0xc7, 0x9b, 0xda, 0xd2, 0x7d,
	0x87, 0x4e, 0x21, 0x7a, 0xe1, 0x52, 0xbd, 0x56, 0x22, 0xcf, 0x72, 0x14, 0x06, 0x19, 0xb2, 0x7f,
	0x1e, 0x5d, 0x40, 0x60, 0xb9, 0x7b, 0xba, 0x65, 0x28, 0xb7, 0x45, 0xdb, 0x6d, 0xc0, 0x3a, 0xb5,
	0xf8, 0xf5, 0x20, 0xca, 0xf2, 0x02, 0x37, 0x0d, 0x2f, 0x65, 0x86, 0x0d, 0xb9, 0x85, 0x51, 0x5a,
	0x63, 0x49, 0x48, 0x3b, 0x92, 0xb9, 0xf3, 0xdb, 0xb3, 0x93, 0xce, 0xeb, 0x6f, 0xa1, 0x03, 0x72,
	0x03, 0xe3, 0x87, 0xa2, 0xd2, 0x17, 0xda, 0xbd, 0x83, 0xd9, 0x3b, 0x18, 0xe9, 0xde, 0xf7, 0xa2,
	0xcf, 0x3a, 0xcf, 0xfd, 0x1c, 0x3a, 0x20, 0x4b, 0xfd, 0x6c, 0x2e, 0xee, 0x77, 0x87, 0x9c, 0x91,
	0xda, 0x43, 0xee, 0x6c, 0xe8, 0xe0, 0x7d, 0x62, 0xdc, 0xe5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x7e, 0x44, 0x53, 0x4e, 0x59, 0x02, 0x00, 0x00,
}
